### ISSUE TITLE
Hide TOC when it intersects with margin content

### ISSUE THREAD

**Issue by rowanc1** [jupyter-book/myst-theme#170]
![image](https://github.com/executablebooks/myst-theme/assets/913249/e76a56bc-76e9-4ed6-9356-bdcabf4319ff)

There is some code @choldgraf has pointed us to here:

https://github.com/executablebooks/sphinx-book-theme/blob/a9794b73cec766e01bee35a96f7d44e22851f278/src/sphinx_book_theme/assets/scripts/index.js#L66

**Comment by choldgraf** [comment]
Note that in the end I didn't make the TOC hide when those two objects overlap directly, but instead opted to make the TOC hide when certain classes of objects were on the screen at all (or 33% up or so), that way the TOC would show and hide preemptively and be less jittery. I think that was a nice balance

**Comment by agoose77** [comment]
@rowanc1 I was checking to see whether we implement the margin directive in myst-theme, or other places, and I can't see that we do. However, the above screenshot seems to imply that we did at one point?

In any case, if we don't currently support it, can we close this issue?

**Comment by rowanc1** [comment]
There are ways to use classes/columns on the blocks to put things in the margins, but it isn't very good to put that burden on the user. I can try and dig up the classes later this week and have a go at implementing the margin directive if you want?

**Comment by agoose77** [comment]
@rowanc1 for this issue my question lies around whether MyST currently supports some-way of putting things in the margins. If we do, regardless of user experience, then is the issue raised by @choldgraf still a problem?

Then, for the directive, that's now tracked in https://github.com/executablebooks/myst-theme/issues/327. I can tackle it in the near term, once I have a sense of what needs doing? Equally happy for you to tackle!

**Comment by choldgraf** [comment]
Just sharing the grid system page of the Myst theme docs, which seems to be the recommended way to control things like margins if I understand

https://executablebooks.github.io/myst-theme/?path=/docs/components-grid-system--docs

**Comment by agoose77** [comment]
Oh, how did that not turn up in any of my searches :facepalm:?

Fab, I am now following. We're talking about something like `col-margin-right`.

**Comment by choldgraf** [comment]
I had the same challenge haha, the only way I found those Myst theme docs was via the GitHub repo URL link. I should have opened a PR for the dev docs, sorry about that!

**Comment by rowanc1** [comment]
There is also an issue at the moment of margins being embedded in admonitions, because these can't pop out of their grid, things look very broken.

**Comment by agoose77** [comment]
Fixed by #373
