### ISSUE TITLE
Light / dark mode does not persist between pages in static export

### ISSUE THREAD

**Issue by choldgraf** [jupyter-book/myst-theme#319]
## Description

The light and dark mode changes back to the default when you navigate between pages. This is on an HTML build and can be demoed here:

https://2i2c.org/report-czi-2021/

For example:

![CleanShot 2024-03-01 at 18 00 46](https://github.com/executablebooks/mystmd/assets/1839645/32bfc5a3-d693-41c3-9208-4716cefb8f8a)

## Proposed solution

Persist the status of light/dark by using an HTML browser window key variable.

**Comment by stevejpurves** [comment]
localstorage is not a good solution for SSR but for static builds we can probably opt out of the cookie and do local storage instead

**Comment by rowanc1** [comment]
As @stevejpurves mentioned, we should continue using cookies for SSR, but switch to local storage for the static render. As local storage is not present on the server, there is a flicker which can be avoided when the theme preference is treated as shared state between server/client (best practice in that scenario).
