### ISSUE TITLE
HTML served with `<img src=http://localhost:3100> even with `HOST=10.0.0.1 myst start --keep-host`

### ISSUE THREAD

**Issue by drewlio** [jupyter-book/myst-theme#342]
### Describe the bug

When I have a fresh install with the mystmd-quickstart, and do a `HOST=10.0.0.1 myst start --keep-host`,

I expect to remotely access `http://10.0.01:3000` and have it serve the entire web page,

but instead, while most assets are loaded from relative links and work fine, `<img src>` tags point to an absolute URL of `http://localhost:3100/...` (see picture below of incorrect links in the client browser)

![image](https://github.com/executablebooks/myst-theme/assets/13006720/b65ff0b4-8f6e-4bf4-91af-3db109035e5f)

However, the server is binding to 10.0.0.1 and will serve the asset file. (see picture below of directly accessing the asset URL with the correct domain instead of `localhost`)

![image](https://github.com/executablebooks/myst-theme/assets/13006720/9b4a4cfc-dbbb-4628-afbd-935d7d6de7cb)

This is a problem for people trying to use mystmd through a SSH connection to the big server where they do their computational work and where their Jupyter notebooks live and run.

To try to help, could it be related to the hardcoded `localhost` below? It seems like this would be fixed if this was a relative path like the other assets.
https://github.com/executablebooks/myst-theme/blob/e549832055fa51faacc1f3966201e659a1365560/themes/book/app/utils/loaders.server.ts#L14

### Reproduce the bug

1. install mystmd
2. download the quickstart
3. set your HOST env variable
4. `myst start --keep-host`

### List your environment

$ myst --version
v1.1.48

$ myst templates list --site book-theme
ID: site/myst/book-theme
Version: 1.0.0

**Comment by drewlio** [comment]
Looks like article-theme does the same thing
https://github.com/executablebooks/myst-theme/blob/e549832055fa51faacc1f3966201e659a1365560/themes/article/app/utils/loaders.server.ts#L14

**Comment by drewlio** [comment]
On the idea of making it a relative path, [RFC3986 Section 5.2.2](https://www.rfc-editor.org/rfc/rfc3986#section-5.2.2) says you can't change the port in a relative path. If you need to change the port, you have to specify the entire "authority" (host:port).

**Comment by LecrisUT** [comment]
> On the idea of making it a relative path, [RFC3986 Section 5.2.2](https://www.rfc-editor.org/rfc/rfc3986#section-5.2.2) says you can't change the port in a relative path. If you need to change the port, you have to specify the entire "authority" (host:port).

I am not sure this is relevant. `myst start` controls what `host:port` are being listened to, and the relative paths should just change according to the paths that are served + the current document/path

About the `utils/loders.server.ts`, I am not sure if that one is related. I wonder if that one is just used to get the pages. What we are after here is to change the link parser itself, so I think it would be in `myst-to-react`, maybe somewhere around
https://github.com/executablebooks/myst-theme/blob/e549832055fa51faacc1f3966201e659a1365560/packages/myst-to-react/src/links/index.tsx#L25-L55

**Comment by LecrisUT** [comment]
Probably worth mentioning the context for the other discussions in `mystmd`. A better solution is to keep all of the paths relative (and add `.html` suffix on `.md` files) in order to make the static site generation more portable

**Comment by stevejpurves** [comment]
I see... tagging these issues https://github.com/executablebooks/mystmd/pull/994 & https://github.com/executablebooks/mystmd/pull/994

so in using relative paths are you suggesting proxying to the content server when running the development server so get around the different port mapping? (I don't follow on the need for the additional .html suffix, though as all content files get .html extensions in the static build -- but I probably need to dig into the other issue a bit more)

**Comment by LecrisUT** [comment]
> so in using relative paths are you suggesting proxying to the content server when running the development server so get around the different port mapping?

Kinda, basically this fixes both the static site generation and serving behind a reverse-proxy because in both cases it will navigate based on whatever url it was served, beit `file://`, `https://`, etc.

> I don't follow on the need for the additional .html suffix

For context, you can check: https://mystmd-temp.readthedocs.io/latest/ which was generated from the static builder. (The site is not navigable). Yes, all html files were downloaded, but the links were those of `react` which did not add the `.html` suffix so that they are navigable. On the other hand `sphinx` always adds `.html` suffix to the page links, mirroring the `.md` file structure.

**Comment by Joseph-Hui** [comment]
I am trying out MyST and I encountered the same issue. I installed `mystmd` with `pip` and the version is 1.3.25.
